---
languageCode: "en-us"
baseurl: "//erikzaadi.com/"
title: "Erik Zaadi"
author: "Erik Zaadi"
layoutdir: "layouts"
contentdir: "content"
publishdir: "public"
indexes:
    category: "categories"
permalinks:
    posts: /:year/:month/:day/:slug/
    pages: /:slug/
metadataformat: "yaml"
theme: "mine"
params:
  description: "The tales of a team leader with passion for dad jokes"
  copyright: "© 2017 erikzaadi.com"
  disqusShortname: erikzaadi
  aboutAuthor: "WebOps Dad"
  twitter : "erikzaadi"
  enableRSS: true
  name : "Erik Zaadi"
  bio : "Loves playing with code, pixels, people, builds and puns"
  googleAnalytics: "UA-8728177-3"
  title404 : "Oh Noez!!"
  subtitle404 : "Well, we got ourselves a 404. Imagine that."
  readMore: "MOAR™ Posts"
  solarizedTheme: "dark"
