#!/usr/bin/env bash
# Recover lost Terraform state: look up the existing resources via the AWS CLI (read-only)
# and write import blocks to imports.tf. Does not run terraform.
#
# Usage:
#   ./terraform/generate-imports.sh
#   then: terraform plan  (expect only imports + aws_acm_certificate_validation creates)
#         terraform apply
#         rm imports.tf
#
# aws_acm_certificate_validation can't be imported, terraform recreates it on apply
# (it only waits for the already-validated cert, no AWS change).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/imports.tf"

export AWS_PROFILE="${AWS_PROFILE:-private}"
export AWS_REGION=us-east-1

HOSTED_ZONE_NAME="erikzaadi.com"
# "domain:cloudfront resource name" - keep in sync with variables.tf, cloudfront.tf and preview.tf
# (the preview A/AAAA records use allow_overwrite, so they don't need importing)
SITES=("erikzaadi.com:main" "slides.erikzaadi.com:slides" "blogpreview.erikzaadi.com:preview")

if [[ -s "$SCRIPT_DIR/terraform.tfstate" ]] \
  && [[ $(jq '.resources | length' "$SCRIPT_DIR/terraform.tfstate") != "0" ]]; then
  echo "[imports] terraform.tfstate already has resources, refusing to generate imports."
  exit 1
fi

echo "[imports] Looking up hosted zone ${HOSTED_ZONE_NAME}..."
ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "${HOSTED_ZONE_NAME}." \
  --no-cli-pager --output json \
  | jq -r --arg name "${HOSTED_ZONE_NAME}." \
    '.HostedZones[] | select(.Name == $name and .Config.PrivateZone == false) | .Id' \
  | sed 's|/hostedzone/||')
[[ -n "$ZONE_ID" ]] || { echo "[imports] Hosted zone not found"; exit 1; }
echo "  ${ZONE_ID}"

DISTRIBUTIONS=$(aws cloudfront list-distributions --no-cli-pager --output json)
CERTS=$(aws acm list-certificates --no-cli-pager --output json)

{
  echo "# Generated by generate-imports.sh - apply once, then delete this file"
  echo ""
} > "$OUT"

for SITE in "${SITES[@]}"; do
  DOMAIN="${SITE%%:*}"
  RESOURCE="${SITE##*:}"
  echo "[imports] ${DOMAIN}"

  DIST_ID=$(jq -r --arg d "$DOMAIN" \
    '[.DistributionList.Items[] | select((.Aliases.Items // []) | index($d))] | if length == 1 then .[0].Id else empty end' \
    <<< "$DISTRIBUTIONS")
  [[ -n "$DIST_ID" ]] || { echo "  expected exactly one distribution with alias ${DOMAIN}"; exit 1; }
  echo "  distribution: ${DIST_ID}"

  CERT_ARN=$(jq -r --arg d "$DOMAIN" \
    '[.CertificateSummaryList[] | select(.DomainName == $d and .Type == "AMAZON_ISSUED" and .InUse == true)] | if length == 1 then .[0].CertificateArn else empty end' \
    <<< "$CERTS")
  [[ -n "$CERT_ARN" ]] || { echo "  expected exactly one in-use AMAZON_ISSUED cert for ${DOMAIN}"; exit 1; }
  echo "  certificate:  ${CERT_ARN}"

  RECORD=$(aws acm describe-certificate --certificate-arn "$CERT_ARN" --no-cli-pager --output json \
    | jq -r --arg d "$DOMAIN" '.Certificate.DomainValidationOptions[] | select(.DomainName == $d) | .ResourceRecord | "\(.Name | rtrimstr("."))_\(.Type)"')
  [[ -n "$RECORD" ]] || { echo "  validation record not found for ${DOMAIN}"; exit 1; }
  echo "  validation:   ${RECORD}"

  cat >> "$OUT" << EOF
import {
  to = aws_cloudfront_distribution.${RESOURCE}
  id = "${DIST_ID}"
}

import {
  to = aws_acm_certificate.site["${DOMAIN}"]
  id = "${CERT_ARN}"
}

import {
  to = aws_route53_record.cert_validation["${DOMAIN}"]
  id = "${ZONE_ID}_${RECORD}"
}

EOF
done

# Account-unique names, terraform can't just recreate these
# (bucket policies / public access blocks / ownership controls are PUTs, no import needed)
echo "[imports] Shared resources"

OAC_ID=$(aws cloudfront list-origin-access-controls --no-cli-pager --output json \
  | jq -r '.OriginAccessControlList.Items[]? | select(.Name == "erikzaadi-com-sites") | .Id')
FUNCTION_EXISTS=$(aws cloudfront describe-function --name erikzaadi-com-index-rewrite \
  --no-cli-pager --output text --query 'FunctionSummary.Name' 2>/dev/null || true)
OIDC_ARN=$(aws iam list-open-id-connect-providers --no-cli-pager --output json \
  | jq -r '.OpenIDConnectProviderList[].Arn | select(endswith("/token.actions.githubusercontent.com"))')
ROLE_EXISTS=$(aws iam get-role --role-name erikzaadi-com-github-deploy \
  --no-cli-pager --output text --query 'Role.RoleName' 2>/dev/null || true)

add_import() {
  echo "  $1 <- $2"
  printf 'import {\n  to = %s\n  id = "%s"\n}\n\n' "$1" "$2" >> "$OUT"
}

[[ -n "$OAC_ID" ]] && add_import aws_cloudfront_origin_access_control.site "$OAC_ID"
[[ -n "$FUNCTION_EXISTS" ]] && add_import aws_cloudfront_function.index_rewrite erikzaadi-com-index-rewrite
[[ -n "$OIDC_ARN" ]] && add_import aws_iam_openid_connect_provider.github "$OIDC_ARN"
if [[ -n "$ROLE_EXISTS" ]]; then
  add_import aws_iam_role.github_deploy erikzaadi-com-github-deploy
  add_import aws_iam_role_policy.github_deploy erikzaadi-com-github-deploy:deploy
fi

echo ""
echo "[imports] Wrote ${OUT}"
echo "[imports] Next: terraform plan, terraform apply, then rm imports.tf"
